services:
  bekendofquest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bekendofquest-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moneyflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Zotov2001
    expose:
      - "8080"

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: moneyflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zotov2001
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - bekendofquest-backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
