name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build and package backend
        run: mvn clean package -DskipTests

      - name: Build backend Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ${{ github.repository_owner }}/moneyflow-backend:latest \
            .

      - name: Build all services via Docker Compose
        run: docker-compose -f docker-compose.yml build
